### ISSUE TITLE
Lesotho: Update DREAMS mapping for upcoming visit from leadership (?)

### ISSUE THREAD

**Issue by gsarfaty** [USAID-OHA-SI/TeamTracking#28]
Lesotho team collected info from partners on which were offering which services by CC. FYI - @nmcdavid as this is follow up to the August conversation. Timing of leadership visit unknown - may have occurred by now? Will inquire.

Data in word format (inconsistent by partner as well), not in template we provided. Reformatting to clean first.

**Comment by gsarfaty** [comment]
Sent draft visual and tidy dataset to OVC Specialist on 10/18. Did not get a response on any needed modifications, so sent check in message on 10/23. OVC Specialist added SI lead for review - awaiting his reply.

**Comment by gsarfaty** [comment]
Hearing nothing, I move to close this issue!

**Comment by nmcdavid** [comment]
I support this

*NASHIVA McDAVID*
Program Analyst, SIEI/SI Team | Office of HIV/AIDS
U.S. AGENCY FOR INTERNATIONAL DEVELOPMENT
2100 Crystal Drive, #9062B, Arlington, VA 22202
(T) 571.551.7222 | (M) 202.679.9219 | nmcdavid@usaid.gov  |  USAID.gov  |
 @USAID
