### ISSUE TITLE
Contribute to TNZ strategy deck for 1/29 FO presentation

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/TeamTracking#55]
Asked by Melinda Wilson for slides around "key issues for TZ" for the front office meeting on Tuesday.

**Comment by achafetz** [comment]
Posted code to [Github](https://github.com/USAID-OHA-SI/misc_scripts/blob/master/R/TZA_COP19_PPL_support.R)

**Comment by achafetz** [comment]
Emailed Melina and Allison with the slide deck. Waiting to hear about whether a call is needed tomorrow.

**Comment by achafetz** [comment]
No further ask or feedback. Closing ticket.

**Comment by lucasrachel** [comment]
Reopening this TZ COP19 Ticket, as Melinda has asked to work with Noah over the next few days to build off of TZ slide deck that Aaron started. FO meeting is slated for next Tuesday, so revised slides should be completed by Monday.

**Comment by noahbartlett** [comment]
Used Gina's template as starting point.

Link to presentation: https://drive.google.com/open?id=1PaDmNHZHKzMmBUN4d0bSWMjPezw7JOTyn1hMjcU-fxs

**Comment by noahbartlett** [comment]
Presentation made to FO.
Closed.
