### ISSUE TITLE
Pull pre-approved FY19Q1 Data from DATIM

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/TeamTracking#78]
FO request via @lucasrachel

**Comment by achafetz** [comment]
Due to size restriction, had to pull down in separate files

Bucket 1: Burundi, Eswatini, Ethiopia, Kenya, Namibia, Rwanda, and Zimbabwe
Bucket 2: Democratic Republic of the Congo, Lesotho, Malawi, Uganda, Nigeria, South Sudan, Ukraine, Vietnam, Zambia
Bucket 3: Angola, Botswana, Cameroon, Cote d’Ivoire, Haiti/Dominican Republic, Mozambique, South Africa, Tanzania, Western Hemisphere/Caribbean/Jamaica

Data is available on [Google Drive](https://drive.google.com/open?id=1V9l1aEDPje56upEN-oRjuPv6NBCfjFc2).

**Comment by achafetz** [comment]
Repulling with updated data

**Comment by achafetz** [comment]
New DATIM data has been downloaded and posted in grouped zipped files due to size (see above) to [Google Drive](https://drive.google.com/open?id=1V9l1aEDPje56upEN-oRjuPv6NBCfjFc2)

**Comment by gsarfaty** [comment]
Logging official request for Angola site x im for q1, if possible and not burdensome! Thanks.

**Comment by achafetz** [comment]
Here's the [site pull for Angola](https://drive.google.com/open?id=1vYZ0Yzf1OIloWiN5GyX7oWLJanw3luNH) from today
